const ProductsData=
[
    {
"id":1,
"category":"Men",
"subCategory":"Coat",
"productName":"Brown LA",
"costPrice":50,
"price":70,
"quantity":60,
"image":"/public/images/coat-men-1.webp"
},
{
"id":2,
"category":"Men",
"subCategory":"Coat",
"productName":"Red & Black",
"costPrice":55,
"price":75,
"quantity":70,
"image":"/public/images/coat-men-2.webp"
},
{
"id":3,
"category":"Men",
"subCategory":"Coat",
"productName":"Black Nikki",
"costPrice":60,
"price":80,
"quantity":80,
"image":"/public/images/coat-men-3.webp"
},
{
"id":4,
"category":"Men",
"subCategory":"Coat",
"productName":"Brown Stalin",
"costPrice":65,
"price":85,
"quantity":90,
"image":"/public/images/coat-men-4.webp"
},
{
"id":5,
"category":"Men",
"subCategory":"Coat",
"productName":"Gray H&M",
"costPrice":70,
"price":90,
"quantity":100,
"image":"/public/images/coat-men-5.webp"
},
{
"id":6,
"category":"Men",
"subCategory":"Coat",
"productName":"Sliver Ganga",
"costPrice":75,
"price":95,
"quantity":110,
"image":"/public/images/coat-men-6.webp"
},
{
"id":7,
"category":"Men",
"subCategory":"Coat",
"productName":"Black Marin",
"costPrice":80,
"price":100,
"quantity":120,
"image":"/public/images/coat-men-7.webp"
},
{
"id":8,
"category":"Men",
"subCategory":"Coat",
"productName":"Army Ganga",
"costPrice":85,
"price":105,
"quantity":130,
"image":"/public/images/coat-men-8.webp"
},
{
"id":9,
"category":"Men",
"subCategory":"Pants",
"productName":"Gray Skini",
"costPrice":50,
"price":70,
"quantity":60,
"image":"/public/images/pants-men-1.webp"
},
{
"id":10,
"category":"Men",
"subCategory":"Pants",
"productName":"Blue OverLA",
"costPrice":55,
"price":75,
"quantity":70,
"image":"/public/images/pants-men-2.webp"
},
{
"id":11,
"category":"Men",
"subCategory":"Pants",
"productName":"Dark Cargo LS",
"costPrice":60,
"price":80,
"quantity":80,
"image":"/public/images/pants-men-3.webp"
},
{
"id":12,
"category":"Men",
"subCategory":"Pants",
"productName":"Black Cut",
"costPrice":65,
"price":85,
"quantity":90,
"image":"/public/images/pants-men-4.webp"
},
{
"id":13,
"category":"Men",
"subCategory":"Pants",
"productName":"Black Skini",
"costPrice":70,
"price":90,
"quantity":100,
"image":"/public/images/pants-men-5.webp"
},
{
"id":14,
"category":"Men",
"subCategory":"Pants",
"productName":"Sky POP",
"costPrice":75,
"price":95,
"quantity":110,
"image":"/public/images/pants-men-6.webp"
},
{
"id":15,
"category":"Men",
"subCategory":"Pants",
"productName":"Pure Blue",
"costPrice":80,
"price":100,
"quantity":120,
"image":"/public/images/pants-men-7.webp"
},
{
"id":16,
"category":"Men",
"subCategory":"Pants",
"productName":"Black OverLA",
"costPrice":85,
"price":105,
"quantity":130,
"image":"/public/images/pants-men-8.webp"
},
{
"id":17,
"category":"Men",
"subCategory":"Pajama",
"productName":"Bunny Flower",
"costPrice":50,
"price":70,
"quantity":60,
"image":"/public/images/pajama-men-1.webp"
},
{
"id":18,
"category":"Men",
"subCategory":"Pajama",
"productName":"Blue OverLA",
"costPrice":55,
"price":75,
"quantity":70,
"image":"/public/images/pajama-men-2.webp"
},
{
"id":19,
"category":"Men",
"subCategory":"Pajama",
"productName":"Bunny Swiki",
"costPrice":60,
"price":80,
"quantity":80,
"image":"/public/images/pajama-men-3.webp"
},
{
"id":20,
"category":"Men",
"subCategory":"Pajama",
"productName":"Bunny Black",
"costPrice":65,
"price":85,
"quantity":90,
"image":"/public/images/pajama-men-4.webp"
},
{
"id":21,
"category":"Men",
"subCategory":"Pajama",
"productName":"Black Oneal",
"costPrice":70,
"price":90,
"quantity":100,
"image":"/public/images/pajama-men-5.webp"
},
{
"id":22,
"category":"Men",
"subCategory":"Pajama",
"productName":"White Pata",
"costPrice":75,
"price":95,
"quantity":110,
"image":"/public/images/pajama-men-6.webp"
},
{
"id":23,
"category":"Men",
"subCategory":"Pajama",
"productName":"OFF-White CA",
"costPrice":80,
"price":100,
"quantity":120,
"image":"/public/images/pajama-men-7.webp"
},
{
"id":24,
"category":"Men",
"subCategory":"Pajama",
"productName":"Gray Pata",
"costPrice":85,
"price":105,
"quantity":130,
"image":"/public/images/pajama-men-8.webp"
},
{
"id":25,
"category":"Men",
"subCategory":"Shirt",
"productName":"Orange & Blue",
"costPrice":50,
"price":70,
"quantity":60,
"image":"/public/images/shirt-men-1.webp"
},
{
"id":26,
"category":"Men",
"subCategory":"Shirt",
"productName":"Brown & OFF-White",
"costPrice":55,
"price":75,
"quantity":70,
"image":"/public/images/shirt-men-2.webp"
},
{
"id":27,
"category":"Men",
"subCategory":"Shirt",
"productName":"Sky & Gray",
"costPrice":60,
"price":80,
"quantity":80,
"image":"/public/images/shirt-men-3.webp"
},
{
"id":28,
"category":"Men",
"subCategory":"Shirt",
"productName":"Green & White",
"costPrice":65,
"price":85,
"quantity":90,
"image":"/public/images/shirt-men-4.webp"
},
{
"id":29,
"category":"Men",
"subCategory":"Shirt",
"productName":"Sky & White",
"costPrice":70,
"price":90,
"quantity":100,
"image":"/public/images/shirt-men-5.webp"
},
{
"id":30,
"category":"Men",
"subCategory":"Shirt",
"productName":"Red & White",
"costPrice":75,
"price":95,
"quantity":110,
"image":"/public/images/shirt-men-6.webp"
},
{
"id":31,
"category":"Men",
"subCategory":"Shirt",
"productName":"Black & White",
"costPrice":80,
"price":100,
"quantity":120,
"image":"/public/images/shirt-men-7.webp"
},
{
"id":32,
"category":"Men",
"subCategory":"Shirt",
"productName":"Gray Pata",
"costPrice":85,
"price":105,
"quantity":130,
"image":"/public/images/shirt-men-8.webp"
},
{
"id":33,
"category":"Men",
"subCategory":"Short",
"productName":"Black & WhiteLine",
"costPrice":50,
"price":70,
"quantity":60,
"image":"/public/images/short-men-1.webp"
},
{
"id":34,
"category":"Men",
"subCategory":"Short",
"productName":"ThunderGG",
"costPrice":55,
"price":75,
"quantity":70,
"image":"/public/images/short-men-2.webp"
},
{
"id":35,
"category":"Men",
"subCategory":"Short",
"productName":"MaginVan",
"costPrice":60,
"price":80,
"quantity":80,
"image":"/public/images/short-men-3.webp"
},
{
"id":36,
"category":"Men",
"subCategory":"Short",
"productName":"Gray BAD",
"costPrice":65,
"price":85,
"quantity":90,
"image":"/public/images/short-men-4.webp"
},
{
"id":37,
"category":"Men",
"subCategory":"Short",
"productName":"OFF-White Calma",
"costPrice":70,
"price":90,
"quantity":100,
"image":"/public/images/short-men-5.webp"
},
{
"id":38,
"category":"Men",
"subCategory":"Short",
"productName":"Sky-FL",
"costPrice":75,
"price":95,
"quantity":110,
"image":"/public/images/short-men-6.webp"
},
{
"id":39,
"category":"Men",
"subCategory":"Short",
"productName":"Silver & White",
"costPrice":80,
"price":100,
"quantity":120,
"image":"/public/images/short-men-7.webp"
},
{
"id":40,
"category":"Men",
"subCategory":"Short",
"productName":"Black Onil",
"costPrice":85,
"price":105,
"quantity":130,
"image":"/public/images/short-men-8.webp"
},
{
"id":41,
"category":"Men",
"subCategory":"T-Shirt",
"productName":"Dark M",
"costPrice":50,
"price":70,
"quantity":60,
"image":"/public/images/tshirt-men-1.webp"
},
{
"id":42,
"category":"Men",
"subCategory":"T-Shirt",
"productName":"White NAM",
"costPrice":55,
"price":75,
"quantity":70,
"image":"/public/images/tshirt-men-2.webp"
},
{
"id":43,
"category":"Men",
"subCategory":"T-Shirt",
"productName":"Green LC13",
"costPrice":60,
"price":80,
"quantity":80,
"image":"/public/images/tshirt-men-3.webp"
},
{
"id":44,
"category":"Men",
"subCategory":"T-Shirt",
"productName":"Oil&White",
"costPrice":65,
"price":85,
"quantity":90,
"image":"/public/images/tshirt-men-4.webp"
},
{
"id":45,
"category":"Men",
"subCategory":"T-Shirt",
"productName":"White&RedLine",
"costPrice":70,
"price":90,
"quantity":100,
"image":"/public/images/tshirt-men-5.webp"
},
{
"id":46,
"category":"Men",
"subCategory":"T-Shirt",
"productName":"Half White&Gray",
"costPrice":75,
"price":95,
"quantity":110,
"image":"/public/images/tshirt-men-6.webp"
},
{
"id":47,
"category":"Men",
"subCategory":"T-Shirt",
"productName":"Orange Dragon",
"costPrice":80,
"price":100,
"quantity":120,
"image":"/public/images/tshirt-men-7.webp"
},
{
"id":48,
"category":"Men",
"subCategory":"T-Shirt",
"productName":"Sky POP",
"costPrice":85,
"price":105,
"quantity":130,
"image":"/public/images/tshirt-men-8.webp"
},
{
"id":49,
"category":"Men",
"subCategory":"Jacket",
"productName":"Black Scalfi",
"costPrice":50,
"price":70,
"quantity":60,
"image":"/public/images/jacket-men-1.webp"
},
{
"id":50,
"category":"Men",
"subCategory":"Jacket",
"productName":"Black Heavy",
"costPrice":55,
"price":75,
"quantity":70,
"image":"/public/images/jacket-men-2.webp"
},
{
"id":51,
"category":"Men",
"subCategory":"Jacket",
"productName":"Blue Scalfi",
"costPrice":60,
"price":80,
"quantity":80,
"image":"/public/images/jacket-men-3.webp"
},
{
"id":52,
"category":"Men",
"subCategory":"Jacket",
"productName":"Black & Panther",
"costPrice":65,
"price":85,
"quantity":90,
"image":"/public/images/jacket-men-4.webp"
},
{
"id":53,
"category":"Men",
"subCategory":"Jacket",
"productName":"Black Wishi",
"costPrice":70,
"price":90,
"quantity":100,
"image":"/public/images/jacket-men-5.webp"
},
{
"id":54,
"category":"Men",
"subCategory":"Jacket",
"productName":"Green Bumb",
"costPrice":75,
"price":95,
"quantity":110,
"image":"/public/images/jacket-men-6.webp"
},
{
"id":55,
"category":"Men",
"subCategory":"Jacket",
"productName":"Off-White Heavy",
"costPrice":80,
"price":100,
"quantity":120,
"image":"/public/images/jacket-men-7.webp"
},
{
"id":56,
"category":"Men",
"subCategory":"Jacket",
"productName":"Pure Silver",
"costPrice":85,
"price":105,
"quantity":130,
"image":"/public/images/jacket-men-8.webp"
},
{
"id":57,
"category":"Men",
"subCategory":"Hoodies",
"productName":"Black Scalfi",
"costPrice":50,
"price":70,
"quantity":60,
"image":"/public/images/ho-men-1.webp"
},
{
"id":58,
"category":"Men",
"subCategory":"Hoodies",
"productName":"Black Heavy",
"costPrice":55,
"price":75,
"quantity":70,
"image":"/public/images/ho-men-2.webp"
},
{
"id":59,
"category":"Men",
"subCategory":"Hoodies",
"productName":"Blue Scalfi",
"costPrice":60,
"price":80,
"quantity":80,
"image":"/public/images/ho-men-3.webp"
},
{
"id":60,
"category":"Men",
"subCategory":"Hoodies",
"productName":"Black & Panther",
"costPrice":65,
"price":85,
"quantity":90,
"image":"/public/images/ho-men-4.webp"
},
{
"id":61,
"category":"Men",
"subCategory":"Hoodies",
"productName":"Black Wishi",
"costPrice":70,
"price":90,
"quantity":100,
"image":"/public/images/ho-men-5.webp"
},
{
"id":62,
"category":"Men",
"subCategory":"Hoodies",
"productName":"Green Bumb",
"costPrice":75,
"price":95,
"quantity":110,
"image":"/public/images/ho-men-6.webp"
},
{
"id":63,
"category":"Men",
"subCategory":"Hoodies",
"productName":"Off-White Heavy",
"costPrice":80,
"price":100,
"quantity":120,
"image":"/public/images/ho-men-7.webp"
},
{
"id":64,
"category":"Men",
"subCategory":"Hoodies",
"productName":"Pure Silver",
"costPrice":85,
"price":105,
"quantity":130,
"image":"/public/images/ho-men-8.webp"
},
{
"id":65,
"category":"Women",
"subCategory":"Coat",
"productName":"SQUARE QUILTED",
"costPrice":50,
"price":70,
"quantity":60,
"image":"/public/images/coat-women-1.webp"
},
{
"id":66,
"category":"Women",
"subCategory":"Coat",
"productName":"BOMBER JACKET",
"costPrice":55,
"price":75,
"quantity":70,
"image":"/public/images/coat-women-2.webp"
},
{
"id":67,
"category":"Women",
"subCategory":"Coat",
"productName":"BASIC JERSEY",
"costPrice":60,
"price":80,
"quantity":80,
"image":"/public/images/coat-women-3.webp"
},
{
"id":68,
"category":"Women",
"subCategory":"Coat",
"productName":"DETAIL GILET",
"costPrice":65,
"price":85,
"quantity":90,
"image":"/public/images/coat-women-4.webp"
},
{
"id":69,
"category":"Women",
"subCategory":"Coat",
"productName":"FUR COAT",
"costPrice":70,
"price":90,
"quantity":100,
"image":"/public/images/coat-women-5.webp"
},
{
"id":70,
"category":"Women",
"subCategory":"Coat",
"productName":"BRIGHT CHECK",
"costPrice":75,
"price":95,
"quantity":110,
"image":"/public/images/coat-women-6.webp"
},
{
"id":71,
"category":"Women",
"subCategory":"Coat",
"productName":"TEDDY FAUX",
"costPrice":80,
"price":100,
"quantity":120,
"image":"/public/images/coat-women-7.webp"
},
{
"id":72,
"category":"Women",
"subCategory":"Coat",
"productName":"TAILORED BLAZER",
"costPrice":85,
"price":105,
"quantity":130,
"image":"/public/images/coat-women-8.webp"
},
{
"id":73,
"category":"Women",
"subCategory":"Dress",
"productName":"Boutique Sequins",
"costPrice":50,
"price":70,
"quantity":60,
"image":"/public/images/dress-women-1.webp"
},
{
"id":74,
"category":"Women",
"subCategory":"Dress",
"productName":"Fine knitting",
"costPrice":55,
"price":75,
"quantity":70,
"image":"/public/images/dress-women-2.webp"
},
{
"id":75,
"category":"Women",
"subCategory":"Dress",
"productName":"RIB ROLL",
"costPrice":60,
"price":80,
"quantity":80,
"image":"/public/images/dress-women-3.webp"
},
{
"id":76,
"category":"Women",
"subCategory":"Dress",
"productName":"Striped Knitted",
"costPrice":65,
"price":85,
"quantity":90,
"image":"/public/images/dress-women-4.webp"
},
{
"id":77,
"category":"Women",
"subCategory":"Dress",
"productName":"Wedding dress",
"costPrice":70,
"price":90,
"quantity":100,
"image":"/public/images/dress-women-5.webp"
},
{
"id":78,
"category":"Women",
"subCategory":"Dress",
"productName":"BRIDESMAID HAND",
"costPrice":75,
"price":95,
"quantity":110,
"image":"/public/images/dress-women-6.webp"
},
{
"id":79,
"category":"Women",
"subCategory":"Dress",
"productName":"PLUS WOVEN",
"costPrice":80,
"price":100,
"quantity":120,
"image":"/public/images/dress-women-7.webp"
},
{
"id":80,
"category":"Women",
"subCategory":"Dress",
"productName":"MONO PRINTED",
"costPrice":85,
"price":105,
"quantity":130,
"image":"/public/images/dress-women-8.webp"
},
{
"id":81,
"category":"Women",
"subCategory":"Pajama",
"productName":"FLOCKED SLOGAN",
"costPrice":50,
"price":70,
"quantity":60,
"image":"/public/images/pajama-women-1.webp"
},
{
"id":82,
"category":"Women",
"subCategory":"Pajama",
"productName":"YORK SUPER",
"costPrice":55,
"price":75,
"quantity":70,
"image":"/public/images/pajama-women-2.webp"
},
{
"id":83,
"category":"Women",
"subCategory":"Pajama",
"productName":"BLACK TALL",
"costPrice":60,
"price":80,
"quantity":80,
"image":"/public/images/pajama-women-3.webp"
},
{
"id":84,
"category":"Women",
"subCategory":"Pajama",
"productName":"GREY RECYCLED",
"costPrice":65,
"price":85,
"quantity":90,
"image":"/public/images/pajama-women-4.webp"
},
{
"id":85,
"category":"Women",
"subCategory":"Pajama",
"productName":"BLACK TALL LEOPARD",
"costPrice":70,
"price":90,
"quantity":100,
"image":"/public/images/pajama-women-5.webp"
},
{
"id":86,
"category":"Women",
"subCategory":"Pajama",
"productName":"LOS ANGELES",
"costPrice":75,
"price":95,
"quantity":110,
"image":"/public/images/pajama-women-6.webp"
},
{
"id":87,
"category":"Women",
"subCategory":"Pajama",
"productName":"WHITE RECYCLED",
"costPrice":80,
"price":100,
"quantity":120,
"image":"/public/images/pajama-women-7.webp"
},
{
"id":88,
"category":"Women",
"subCategory":"Pajama",
"productName":"TONAL COLOUR BLOCK",
"costPrice":85,
"price":105,
"quantity":130,
"image":"/public/images/pajama-women-8.webp"
},
{
"id":89,
"category":"Women",
"subCategory":"Shirt",
"productName":"BROWN",
"costPrice":50,
"price":70,
"quantity":60,
"image":"/public/images/shirt-women-1.webp"
},
{
"id":90,
"category":"Women",
"subCategory":"Shirt",
"productName":"SATIN LEOPARD",
"costPrice":55,
"price":75,
"quantity":70,
"image":"/public/images/shirt-women-2.webp"
},
{
"id":91,
"category":"Women",
"subCategory":"Shirt",
"productName":"BEIGE PLUS",
"costPrice":60,
"price":80,
"quantity":80,
"image":"/public/images/shirt-women-3.webp"
},
{
"id":92,
"category":"Women",
"subCategory":"Shirt",
"productName":"ZEBRA COLD",
"costPrice":65,
"price":85,
"quantity":90,
"image":"/public/images/shirt-women-4.webp"
},
{
"id":93,
"category":"Women",
"subCategory":"Shirt",
"productName":"BLACK HIGH",
"costPrice":70,
"price":90,
"quantity":100,
"image":"/public/images/shirt-women-5.webp"
},
{
"id":94,
"category":"Women",
"subCategory":"Shirt",
"productName":"GREEN PLUS",
"costPrice":75,
"price":95,
"quantity":110,
"image":"/public/images/shirt-women-6.webp"
},
{
"id":95,
"category":"Women",
"subCategory":"Shirt",
"productName":"RED BOW",
"costPrice":80,
"price":100,
"quantity":120,
"image":"/public/images/shirt-women-7.webp"
},
{
"id":96,
"category":"Women",
"subCategory":"Shirt",
"productName":"BEIGE SHEER",
"costPrice":85,
"price":105,
"quantity":130,
"image":"/public/images/shirt-women-8.webp"
},
{
"id":97,
"category":"Women",
"subCategory":"Hoodies",
"productName":"GRAY FLOCKED",
"costPrice":50,
"price":70,
"quantity":60,
"image":"/public/images/hodie-women-1.webp"
},
{
"id":98,
"category":"Women",
"subCategory":"Hoodies",
"productName":"Dark Residential",
"costPrice":55,
"price":75,
"quantity":70,
"image":"/public/images/hodie-women-2.webp"
},
{
"id":99,
"category":"Women",
"subCategory":"Hoodies",
"productName":"TIE DYE OFFICIAL",
"costPrice":60,
"price":80,
"quantity":80,
"image":"/public/images/hodie-women-3.webp"
},
{
"id":100,
"category":"Women",
"subCategory":"Hoodies",
"productName":"DECEMBER 25TH",
"costPrice":65,
"price":85,
"quantity":90,
"image":"/public/images/hodie-women-4.webp"
},
{
"id":101,
"category":"Women",
"subCategory":"Hoodies",
"productName":"VARSITY SWEATER",
"costPrice":70,
"price":90,
"quantity":100,
"image":"/public/images/hodie-women-5.webp"
},
{
"id":102,
"category":"Women",
"subCategory":"Hoodies",
"productName":"NEW YORK SUPER",
"costPrice":75,
"price":95,
"quantity":110,
"image":"/public/images/hodie-women-6.webp"
},
{
"id":103,
"category":"Women",
"subCategory":"Hoodies",
"productName":"PINK MULTI",
"costPrice":80,
"price":100,
"quantity":120,
"image":"/public/images/hodie-women-7.webp"
},
{
"id":104,
"category":"Women",
"subCategory":"Hoodies",
"productName":"PHOENIX PRINTED",
"costPrice":85,
"price":105,
"quantity":130,
"image":"/public/images/hodie-women-8.webp"
},
{
"id":105,
"category":"Women",
"subCategory":"T-Shirt",
"productName":"POCKET",
"costPrice":50,
"price":70,
"quantity":60,
"image":"/public/images/tshirt-women-1.webp"
},
{
"id":106,
"category":"Women",
"subCategory":"T-Shirt",
"productName":"BROWN PETITE",
"costPrice":55,
"price":75,
"quantity":70,
"image":"/public/images/tshirt-women-2.webp"
},
{
"id":107,
"category":"Women",
"subCategory":"T-Shirt",
"productName":"BEIGE SHIRT",
"costPrice":60,
"price":80,
"quantity":80,
"image":"/public/images/tshirt-women-3.webp"
},
{
"id":108,
"category":"Women",
"subCategory":"T-Shirt",
"productName":"Striped Knitted",
"costPrice":65,
"price":85,
"quantity":90,
"image":"/public/images/tshirt-women-4.webp"
},
{
"id":109,
"category":"Women",
"subCategory":"T-Shirt",
"productName":"BLACK FEATHER",
"costPrice":70,
"price":90,
"quantity":100,
"image":"/public/images/tshirt-women-5.webp"
},
{
"id":110,
"category":"Women",
"subCategory":"T-Shirt",
"productName":"GREEN SEQUIN",
"costPrice":75,
"price":95,
"quantity":110,
"image":"/public/images/tshirt-women-6.webp"
},
{
"id":111,
"category":"Women",
"subCategory":"T-Shirt",
"productName":"BLACK SATIN",
"costPrice":80,
"price":100,
"quantity":120,
"image":"/public/images/tshirt-women-7.webp"
},
{
"id":112,
"category":"Women",
"subCategory":"T-Shirt",
"productName":"MONO PRINTED",
"costPrice":85,
"price":105,
"quantity":130,
"image":"/public/images/tshirt-women-8.webp"
},
{
"id":113,
"category":"Women",
"subCategory":"Jacket",
"productName":"BLACK PADDED",
"costPrice":50,
"price":70,
"quantity":60,
"image":"/public/images/jacket-women-1.webp"
},
{
"id":114,
"category":"Women",
"subCategory":"Jacket",
"productName":"TAILORED",
"costPrice":55,
"price":75,
"quantity":70,
"image":"/public/images/jacket-women-2.webp"
},
{
"id":115,
"category":"Women",
"subCategory":"Jacket",
"productName":"TEXTURED FAUX",
"costPrice":60,
"price":80,
"quantity":80,
"image":"/public/images/jacket-women-3.webp"
},
{
"id":116,
"category":"Women",
"subCategory":"Jacket",
"productName":"TEDDY FUR BOMBER",
"costPrice":65,
"price":85,
"quantity":90,
"image":"/public/images/jacket-women-4.webp"
},
{
"id":117,
"category":"Women",
"subCategory":"Jacket",
"productName":"BREASTED",
"costPrice":70,
"price":90,
"quantity":100,
"image":"/public/images/jacket-women-5.webp"
},
{
"id":118,
"category":"Women",
"subCategory":"Jacket",
"productName":"TRIM PU BELTED",
"costPrice":75,
"price":95,
"quantity":110,
"image":"/public/images/jacket-women-6.webp"
},
{
"id":119,
"category":"Women",
"subCategory":"Jacket",
"productName":"CIRCLE QUILTED",
"costPrice":80,
"price":100,
"quantity":120,
"image":"/public/images/jacket-women-7.webp"
},
{
"id":120,
"category":"Women",
"subCategory":"Jacket",
"productName":"VINTAGE",
"costPrice":85,
"price":105,
"quantity":130,
"image":"/public/images/jacket-women-8.webp"
},
{
"id":121,
"category":"Women",
"subCategory":"Pants",
"productName":"HIGH WAISTED",
"costPrice":50,
"price":70,
"quantity":60,
"image":"/public/images/pant-women-1.webp"
},
{
"id":122,
"category":"Women",
"subCategory":"Pants",
"productName":"PETITE TIE DYE",
"costPrice":55,
"price":75,
"quantity":70,
"image":"/public/images/pant-women-2.webp"
},
{
"id":123,
"category":"Women",
"subCategory":"Pants",
"productName":"PLUS EXTREME",
"costPrice":60,
"price":80,
"quantity":80,
"image":"/public/images/pant-women-3.webp"
},
{
"id":124,
"category":"Women",
"subCategory":"Pants",
"productName":"SHAPER LACE",
"costPrice":65,
"price":85,
"quantity":90,
"image":"/public/images/pant-women-4.webp"
},
{
"id":125,
"category":"Women",
"subCategory":"Pants",
"productName":"HIGH RISE",
"costPrice":70,
"price":90,
"quantity":100,
"image":"/public/images/pant-women-5.webp"
},
{
"id":126,
"category":"Women",
"subCategory":"Pants",
"productName":"PLUS SIZE ORGANIC",
"costPrice":75,
"price":95,
"quantity":110,
"image":"/public/images/pant-women-6.webp"
},
{
"id":127,
"category":"Women",
"subCategory":"Pants",
"productName":"BUTT SHAPER",
"costPrice":80,
"price":100,
"quantity":120,
"image":"/public/images/pant-women-7.webp"
},
{
"id":128,
"category":"Women",
"subCategory":"Pants",
"productName":"GIRL TALK",
"costPrice":85,
"price":105,
"quantity":130,
"image":"/public/images/pant-women-8.webp"
},
{
"id":129,
"category":"Kids",
"subCategory":"Jacket",
"productName":"Army jacket",
"costPrice":50,
"price":70,
"quantity":60,
"image":"/public/images/jacket-kids-1.webp"
},
{
"id":130,
"category":"Kids",
"subCategory":"Jacket",
"productName":"White Tiger",
"costPrice":55,
"price":75,
"quantity":70,
"image":"/public/images/jacket-kids-2.webp"
},
{
"id":131,
"category":"Kids",
"subCategory":"Jacket",
"productName":"Teddy Lined",
"costPrice":60,
"price":80,
"quantity":80,
"image":"/public/images/jacket-kids-3.webp"
},
{
"id":132,
"category":"Kids",
"subCategory":"Jacket",
"productName":"Hoded Quilted",
"costPrice":65,
"price":85,
"quantity":90,
"image":"/public/images/jacket-kids-4.webp"
},
{
"id":133,
"category":"Kids",
"subCategory":"Jacket",
"productName":"Blue Jacket",
"costPrice":70,
"price":90,
"quantity":100,
"image":"/public/images/jacket-kids-5.webp"
},
{
"id":134,
"category":"Kids",
"subCategory":"Jacket",
"productName":"Heavy Blue",
"costPrice":75,
"price":95,
"quantity":110,
"image":"/public/images/jacket-kids-6.webp"
},
{
"id":135,
"category":"Kids",
"subCategory":"Jacket",
"productName":"Tinted light",
"costPrice":80,
"price":100,
"quantity":120,
"image":"/public/images/jacket-kids-7.webp"
},
{
"id":136,
"category":"Kids",
"subCategory":"Jacket",
"productName":"Green Scalfi",
"costPrice":85,
"price":105,
"quantity":130,
"image":"/public/images/jacket-kids-8.webp"
},
{
"id":137,
"category":"Kids",
"subCategory":"Pajama",
"productName":"Black&residential",
"costPrice":50,
"price":70,
"quantity":60,
"image":"/public/images/pajama-kids-1.webp"
},
{
"id":138,
"category":"Kids",
"subCategory":"Pajama",
"productName":"Cartoon Style",
"costPrice":55,
"price":75,
"quantity":70,
"image":"/public/images/pajama-kids-2.webp"
},
{
"id":139,
"category":"Kids",
"subCategory":"Pajama",
"productName":"Happy Color",
"costPrice":60,
"price":80,
"quantity":80,
"image":"/public/images/pajama-kids-3.webp"
},
{
"id":140,
"category":"Kids",
"subCategory":"Pajama",
"productName":"Looney Tunes",
"costPrice":65,
"price":85,
"quantity":90,
"image":"/public/images/pajama-kids-4.webp"
},
{
"id":141,
"category":"Kids",
"subCategory":"Pajama",
"productName":"Dark Style",
"costPrice":70,
"price":90,
"quantity":100,
"image":"/public/images/pajama-kids-5.webp"
},
{
"id":142,
"category":"Kids",
"subCategory":"Pajama",
"productName":"White Pajama",
"costPrice":75,
"price":95,
"quantity":110,
"image":"/public/images/pajama-kids-6.webp"
},
{
"id":143,
"category":"Kids",
"subCategory":"Pajama",
"productName":"Light Color",
"costPrice":80,
"price":100,
"quantity":120,
"image":"/public/images/pajama-kids-7.webp"
},
{
"id":144,
"category":"Kids",
"subCategory":"Pajama",
"productName":"Baby Color",
"costPrice":85,
"price":105,
"quantity":130,
"image":"/public/images/pajama-kids-8.webp"
},
{
"id":145,
"category":"Kids",
"subCategory":"Pants",
"productName":"Black Jeans",
"costPrice":50,
"price":70,
"quantity":60,
"image":"/public/images/pants-kids-1.webp"
},
{
"id":146,
"category":"Kids",
"subCategory":"Pants",
"productName":"Blue Skini",
"costPrice":55,
"price":75,
"quantity":70,
"image":"/public/images/pants-kids-2.webp"
},
{
"id":147,
"category":"Kids",
"subCategory":"Pants",
"productName":"Black Jeans",
"costPrice":60,
"price":80,
"quantity":80,
"image":"/public/images/pants-kids-3.webp"
},
{
"id":148,
"category":"Kids",
"subCategory":"Pants",
"productName":"Girl Style",
"costPrice":65,
"price":85,
"quantity":90,
"image":"/public/images/pants-kids-4.webp"
},
{
"id":149,
"category":"Kids",
"subCategory":"Pants",
"productName":"Light Blue",
"costPrice":70,
"price":90,
"quantity":100,
"image":"/public/images/pants-kids-5.webp"
},
{
"id":150,
"category":"Kids",
"subCategory":"Pants",
"productName":"Star Style",
"costPrice":75,
"price":95,
"quantity":110,
"image":"/public/images/pants-kids-6.webp"
},
{
"id":151,
"category":"Kids",
"subCategory":"Pants",
"productName":"Baby Jeans",
"costPrice":80,
"price":100,
"quantity":120,
"image":"/public/images/pants-kids-7.webp"
},
{
"id":152,
"category":"Kids",
"subCategory":"Pants",
"productName":"Baby Cartoon",
"costPrice":85,
"price":105,
"quantity":130,
"image":"/public/images/pants-kids-8.webp"
},
{
"id":153,
"category":"Kids",
"subCategory":"T-Shirt",
"productName":"Red TEO",
"costPrice":50,
"price":70,
"quantity":60,
"image":"/public/images/tshirt-kids-1.webp"
},
{
"id":154,
"category":"Kids",
"subCategory":"T-Shirt",
"productName":"Cool Pink",
"costPrice":55,
"price":75,
"quantity":70,
"image":"/public/images/tshirt-kids-2.webp"
},
{
"id":155,
"category":"Kids",
"subCategory":"T-Shirt",
"productName":"England",
"costPrice":60,
"price":80,
"quantity":80,
"image":"/public/images/tshirt-kids-3.webp"
},
{
"id":156,
"category":"Kids",
"subCategory":"T-Shirt",
"productName":"Black Tshirt",
"costPrice":65,
"price":85,
"quantity":90,
"image":"/public/images/tshirt-kids-4.webp"
},
{
"id":157,
"category":"Kids",
"subCategory":"T-Shirt",
"productName":"Sport CANV",
"costPrice":70,
"price":90,
"quantity":100,
"image":"/public/images/tshirt-kids-5.webp"
},
{
"id":158,
"category":"Kids",
"subCategory":"T-Shirt",
"productName":"Red Dark",
"costPrice":75,
"price":95,
"quantity":110,
"image":"/public/images/tshirt-kids-6.webp"
},
{
"id":159,
"category":"Kids",
"subCategory":"T-Shirt",
"productName":"Black Ohel",
"costPrice":80,
"price":100,
"quantity":120,
"image":"/public/images/tshirt-kids-7.webp"
},
{
"id":160,
"category":"Kids",
"subCategory":"T-Shirt",
"productName":"Light Baby",
"costPrice":85,
"price":105,
"quantity":130,
"image":"/public/images/tshirt-kids-8.webp"
},
{
"id":161,
"category":"Kids",
"subCategory":"Short",
"productName":"Wide Belt",
"costPrice":50,
"price":70,
"quantity":60,
"image":"/public/images/short-kids-1.webp"
},
{
"id":162,
"category":"Kids",
"subCategory":"Short",
"productName":"Girle Mode",
"costPrice":55,
"price":75,
"quantity":70,
"image":"/public/images/short-kids-2.webp"
},
{
"id":163,
"category":"Kids",
"subCategory":"Short",
"productName":"Uniform Short",
"costPrice":60,
"price":80,
"quantity":80,
"image":"/public/images/short-kids-3.webp"
},
{
"id":164,
"category":"Kids",
"subCategory":"Short",
"productName":"Waist Denim",
"costPrice":65,
"price":85,
"quantity":90,
"image":"/public/images/short-kids-4.webp"
},
{
"id":165,
"category":"Kids",
"subCategory":"Short",
"productName":"Uniform Boy",
"costPrice":70,
"price":90,
"quantity":100,
"image":"/public/images/short-kids-5.webp"
},
{
"id":166,
"category":"Kids",
"subCategory":"Short",
"productName":"Jeans Boy",
"costPrice":75,
"price":95,
"quantity":110,
"image":"/public/images/short-kids-6.webp"
},
{
"id":167,
"category":"Kids",
"subCategory":"Short",
"productName":"Derle",
"costPrice":80,
"price":100,
"quantity":120,
"image":"/public/images/short-kids-7.webp"
},
{
"id":168,
"category":"Kids",
"subCategory":"Short",
"productName":"Short Decent",
"costPrice":85,
"price":105,
"quantity":130,
"image":"/public/images/short-kids-8.webp"
},
{
"id":169,
"category":"Kids",
"subCategory":"Hoodies",
"productName":"Cartoon Fees",
"costPrice":50,
"price":70,
"quantity":60,
"image":"/public/images/hodies-kids-1.webp"
},
{
"id":170,
"category":"Kids",
"subCategory":"Hoodies",
"productName":"Gray Cartoon",
"costPrice":55,
"price":75,
"quantity":70,
"image":"/public/images/hodies-kids-2.webp"
},
{
"id":171,
"category":"Kids",
"subCategory":"Hoodies",
"productName":"Red Hoodies",
"costPrice":60,
"price":80,
"quantity":80,
"image":"/public/images/hodies-kids-3.webp"
},
{
"id":172,
"category":"Kids",
"subCategory":"Hoodies",
"productName":"Long Loodies",
"costPrice":65,
"price":85,
"quantity":90,
"image":"/public/images/hodies-kids-4.webp"
},
{
"id":173,
"category":"Kids",
"subCategory":"Hoodies",
"productName":"Black Hoodies",
"costPrice":70,
"price":90,
"quantity":100,
"image":"/public/images/hodies-kids-5.webp"
},
{
"id":174,
"category":"Kids",
"subCategory":"Hoodies",
"productName":"Plain Blue",
"costPrice":75,
"price":95,
"quantity":110,
"image":"/public/images/hodies-kids-6.webp"
},
{
"id":175,
"category":"Kids",
"subCategory":"Hoodies",
"productName":"Plain Hoodies",
"costPrice":80,
"price":100,
"quantity":120,
"image":"/public/images/hodies-kids-7.webp"
},
{
"id":176,
"category":"Kids",
"subCategory":"Hoodies",
"productName":"England Hoodies",
"costPrice":85,
"price":105,
"quantity":130,
"image":"/public/images/hodies-kids-8.webp"
},
{
"id":177,
"category":"Kids",
"subCategory":"Hat",
"productName":"Colorful Cap",
"costPrice":50,
"price":70,
"quantity":60,
"image":"/public/images/hat-kids-1.webp"
},
{
"id":178,
"category":"Kids",
"subCategory":"Hat",
"productName":"Striped Cap",
"costPrice":55,
"price":75,
"quantity":70,
"image":"/public/images/hat-kids-2.webp"
},
{
"id":179,
"category":"Kids",
"subCategory":"Hat",
"productName":"Blue Cap",
"costPrice":60,
"price":80,
"quantity":80,
"image":"/public/images/hat-kids-3.webp"
},
{
"id":180,
"category":"Kids",
"subCategory":"Hat",
"productName":"Pom Decor",
"costPrice":65,
"price":85,
"quantity":90,
"image":"/public/images/hat-kids-4.webp"
},
{
"id":181,
"category":"Kids",
"subCategory":"Hat",
"productName":"Color Gradation",
"costPrice":70,
"price":90,
"quantity":100,
"image":"/public/images/hat-kids-5.webp"
},
{
"id":182,
"category":"Kids",
"subCategory":"Hat",
"productName":"Light Color",
"costPrice":75,
"price":95,
"quantity":110,
"image":"/public/images/hat-kids-6.webp"
},
{
"id":183,
"category":"Kids",
"subCategory":"Hat",
"productName":"Red Cap",
"costPrice":80,
"price":100,
"quantity":120,
"image":"/public/images/hat-kids-7.webp"
},
{
"id":184,
"category":"Kids",
"subCategory":"Hat",
"productName":"Plain Cap",
"costPrice":85,
"price":105,
"quantity":130,
"image":"/public/images/hat-kids-8.webp"
},
{
"id":185,
"category":"Kids",
"subCategory":"Dress",
"productName":"Floral Ruffle",
"costPrice":50,
"price":70,
"quantity":60,
"image":"/public/images/dress-kids-1.webp"
},
{
"id":186,
"category":"Kids",
"subCategory":"Dress",
"productName":"Solid Lantern",
"costPrice":55,
"price":75,
"quantity":70,
"image":"/public/images/dress-kids-2.webp"
},
{
"id":187,
"category":"Kids",
"subCategory":"Dress",
"productName":"Sequin Party",
"costPrice":60,
"price":80,
"quantity":80,
"image":"/public/images/dress-kids-3.webp"
},
{
"id":188,
"category":"Kids",
"subCategory":"Dress",
"productName":"Long Sleeves",
"costPrice":65,
"price":85,
"quantity":90,
"image":"/public/images/dress-kids-4.webp"
},
{
"id":189,
"category":"Kids",
"subCategory":"Dress",
"productName":"Ruffle Trim",
"costPrice":70,
"price":90,
"quantity":100,
"image":"/public/images/dress-kids-5.webp"
},
{
"id":190,
"category":"Kids",
"subCategory":"Dress",
"productName":"White Dress",
"costPrice":75,
"price":95,
"quantity":110,
"image":"/public/images/dress-kids-6.webp"
},
{
"id":191,
"category":"Kids",
"subCategory":"Dress",
"productName":"Lively Dress",
"costPrice":80,
"price":100,
"quantity":120,
"image":"/public/images/dress-kids-7.webp"
},
{
"id":192,
"category":"Kids",
"subCategory":"Dress",
"productName":"Colorful Dress",
"costPrice":85,
"price":105,
"quantity":130,
"image":"/public/images/dress-kids-8.webp"
},
]
export default ProductsData;